<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Mew.Workbench</RootNamespace>
    <AssemblyName>Mew.Workbench</AssemblyName>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aprillz.MewUI" Version="0.19.1" />
    <PackageReference Include="Aprillz.MewUI.MewDock" Version="0.19.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
  </ItemGroup>

</Project>
