<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Mewoo.Abstractions\Mewoo.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aprillz.MewUI" Version="0.15.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

