<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Mew.Launcher</RootNamespace>
    <AssemblyName>Mew.Launcher</AssemblyName>
    <MewUIBackend>Direct2D</MewUIBackend>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mew.Workbench\Mew.Workbench.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aprillz.MewUI" Version="0.19.1" />
    <PackageReference Include="Aprillz.MewUI.MewDock" Version="0.19.1" />
  </ItemGroup>

</Project>
